#!/bin//sh

NO_DIFF_STAGE="git diff --exit-code"
NO_DIFF_REPO="git diff --cached --exit-code"

RELEASE_CMD="gulp release-git"
BUILD_CMD="gulp build:src"

$BUILD_CMD 
if ! $NO_DIFF_STAGE; then
  echo -n "detected unstaged changes."
else
  if $NO_DIFF_REPO; then
    echo "not modified."
    exit 0
  fi

  if ! $RELEASE_CMD; then
    echo -n "running pre-release task failed."
  elif ! $NO_DIFF_STAGE; then
    echo -n "detected unstaged changes."
  else
    echo "succeeded"
    exit 0
  fi
fi

echo ' commit canceled.'
exit 1


